### ISSUE TITLE
Biotracks e Android 5.1.1 Lollipop

### ISSUE THREAD

**Issue by schmaedech** [schmaedech/biotracks#2]
Foi atualizado a nova versão Android 5.1.1 Lollipop e o Biotracks travou.
desinstalei e instalei o biotracks e nada.
O que pode ter acontecido?

**Comment by ghost** [comment]
alguns erros corrigidos. ainda tem erro ao dar stop, mas nada que impede de funcionar. e eh soh nessa versao do android 5.1
